version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            flake8

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
